### ISSUE TITLE
Chrome Full Screen on MBP (2880 x 1800) / potential board resize

### ISSUE THREAD

**Issue by thegoldenpower** [jkk/shinkgs#123]
I am not sure if this is helpful, but when I hit full screen on my MBP (2880 x 1800) in Chrome, I get this. Is the board supposed to resize? I recall seeing that the client was optimized for tablet.

If this isn't an issue let me know and I'll delete it (or you can if possible on GH) :)

<img width="1440" alt="screen shot 2017-05-08 at 10 22 49 pm" src="https://cloud.githubusercontent.com/assets/24276545/25833275/fd7cb390-343d-11e7-9931-4bb9f8cf2c6e.png">

**Comment by jkk** [comment]
This is a legit thing to improve but going to close this favor of issue #122, which has some specific ideas brewing

**Comment by jkk** [comment]
Thanks for the report regardless - helps prioritize what gets done!
