### ISSUE TITLE
Unable to view demo game

### ISSUE THREAD

**Issue by beejunk** [jkk/shinkgs#138]
I attempted to watch the Ke Jie vs. AlphaGo game today (created as a demo game by the USGO2 account), but it would not load up. The console displayed these errors:

XML Parsing Error: syntax error Location: https://www.gokgs.com/json-cors/access Line Number 1, Column 1:  access:1:1
TypeError: e.players.white is undefined

I'm guessing the second error is the more important one.

**Comment by jkk** [comment]
Sorry about that. I have a fix I'll be pushing soon.

**Comment by jkk** [comment]
Fixed in commit 8923e2d02189
