### ISSUE TITLE
(Easy/Medium) Right Clicking Names

### ISSUE THREAD

**Issue by Clossius** [jkk/shinkgs#175]
Okay, I know you can left click names to open profiles...But I have right clicked names on SO MANY TIMES!! lol Maybe make a sub menu when right clicking? KGS has this feature so it is hard wired into my brain...lol

**Comment by hadim** [comment]
I am not sure we want this since right-click in a desktop browser is meant for browser menu and it also does not exist on mobile/tablet.

Feel free to reopen and discuss it if needed.
