### ISSUE TITLE
(Bug) (Easy) Button Size

### ISSUE THREAD

**Issue by Clossius** [jkk/shinkgs#183]
The moment right before the window size makes the UI change for phone sizes there is a small bug where the text + image are bigger than the button and they overlap it.

To recreate simple adjust your window size slowly to the point right before the UI change.

![bug](https://user-images.githubusercontent.com/29341768/40136858-8fdf2074-590e-11e8-85f6-62d7e1c935cf.PNG)

**Comment by KevinSpevak** [comment]
What browser are you using? I'm getting slightly different behavior where only the challenges appears on two lines 

<img width="727" alt="screen shot 2018-05-17 at 1 24 58 am" src="https://user-images.githubusercontent.com/6686576/40165731-9754076c-5971-11e8-9e35-03dee7bb546a.png">

**Comment by Clossius** [comment]
Chrome, I can do the same thing. I was playing around with it and was able to do both.

![bug2](https://user-images.githubusercontent.com/29341768/40180999-b4dc4fba-59ad-11e8-8f2b-d61bafb8ed6d.PNG)

**Comment by KevinSpevak** [comment]
oh interesting, it's just a width of window based thing? Because I tried decreasing the width 1 pixel at a time and never got both overflowing.

**Comment by steppefox** [comment]
@leeschumacher this issue could be probably closed/resolved
