### ISSUE TITLE
Dev status

### ISSUE THREAD

**Issue by hadim** [jkk/shinkgs#192]
The last commit has been pushed last May. I would like to know what is the status of the development? I am asking because I am considering contributing to this project  (React 16 migration + some small features addition) and I would prefer to know the development status first.

ping @jkk

**Comment by jkk** [comment]
Hi @hadim. Development is on the back burner for me personally. I have too much going on with work and life to contribute much code-wise. But I'd love to see others jumping in. I'm more than willing to hand over commit rights to anyone serious about helping, and offer guidance when I can.
