### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by hadim** [jkk/shinkgs#194]
It's good for reproducibility and track regressions.

**Comment by jkk** [comment]
+1. I'd also love to see integration with now.sh e.g. with https://zeit.co/blog/now-for-github. I created a shinkgs team at zeit.co but haven't switched over the production deployment to it yet (it's not obvious how to transfer sub-domains between accounts, and I haven't dug very deeply into figuring it out)

**Comment by hadim** [comment]
Ok, so I'll let you know setup the integration with zeit.co for deployment an I will set up a Travis on my side to be able to build and test the code for each commit.
