### ISSUE TITLE
Various cleanup

### ISSUE THREAD

**Issue by hadim** [jkk/shinkgs#200]
@jkk I need you for this.

- Is that important to keep the `kgs-api` folder? Same for the paragraph in the README about it. Since it's only about the old API, I guess it's kind of deprecate right? Or you think in the future we should be able to run a fake KGS server locally for development?

- Do you still use the `server/` folder? It seems to be some boilerplate to make it work on the official URL. I see you used to use it for the now deployment but it seems to work just well without. Let me know if I can remove this folder.

**Comment by jkk** [comment]
1. yeah kgs-api was from before there was an official, CORS-friendly API endpoint. I wasn't sure if there was any intention of bringing it back, maybe if the API gets opened source. In the meantime it's not being used.

2. server is still used for production deployment. For Safari, requests to the API need to be proxied, or third-party cookies won't work. IIRC it also handles wildcard routes, whereas a normal now.sh single-page app deployment doesn't (at least, that was the case the last time I set things up a while back). It could also be helpful if it ever gets deployed to other environments.

**Comment by hadim** [comment]
Got you.
