### ISSUE TITLE
Possible to create challenge in a specific room?

### ISSUE THREAD

**Issue by pt8o** [jkk/shinkgs#205]
I'm not sure if I just missed an option in the UI! I'm trying to create a challenge in the Canadian Room. I've joined the Canadian Room and can chat in that room, but I can't seem to create a challenge there. 

Under the Play and Watch tabs I'm also unable to select the Canadian Room; it seems to give me a choice of random rooms? Or maybe the most popular?

In any case, the "Create Challenge" button creates a new challenge in the English Game Room, no matter what room I'm currently viewing, and I don't see a way to change it.

**Comment by dnp87** [comment]
Hello. It's not currently implemented, but there's a pull request for the feature.
