### ISSUE TITLE
Really easy to accidently click profile pic when going back/forward on mobile

### ISSUE THREAD

**Issue by hakanw** [jkk/shinkgs#96]
Thanks for Shin KGS, it's great!

The profile pic of player 2 is too close to the back/forward buttons if you watch a game, making it really easy to accidently click the picture when you are stepping through a game (happened to me many times while watching some games).

<img width="444" alt="skarmavbild 2017-04-25 kl 19 43 30" src="https://cloud.githubusercontent.com/assets/100824/25399459/d440a55c-29ef-11e7-9ce7-f45f32c9f473.png">

I would vote for keeping the player boxes in the top instead, it somehow feels more natural. And preferably keep some distance between important clickable elementsto avoid misclicks.

**Comment by hakanw** [comment]
For the same reason (big thumbs), maybe it would be better to keep one arrow on each side in the slider, so you can much more easily hit the right direction.

**Comment by jkk** [comment]
Agreed the buttons aren't ideal. A quick fix would be to not make the profile pic clickable on mobile.

I do like having the buttons adjacent - it allows you to go forward/back with minimal movement. I am all in favor of making them big and easy to press, though.

About moving the profile pics to the top - the main reason they are below is for smaller screens, so the board fits above the fold. I'll think about it though.

**Comment by jkk** [comment]
@hakanw I hacked in a transparent div that makes it harder to accidentally tap name or avatar:

<img width="166" alt="screen shot 2017-05-06 at 5 57 15 pm" src="https://cloud.githubusercontent.com/assets/5173/25776199/2365c344-3286-11e7-8e2b-c5df2219bc2f.png">

Hopefully that improves the situation. If not we can try doing more.
